title: Roy Jing Yang
author:
  name: Roy Jing Yang
  avatar: icon.jpg 
  bio: process mining researcher
  email: roy.j.yang@qut.edu.au
  linkedin: https://www.linkedin.com/in/jing-yang-246507198/
  github: https://github.com/roy-jingyang
  motto: “不以物喜，不以己悲”（<宋>范仲淹 1046）

theme: jekyll-theme-minimal
show_downloads: false